title: DevOps Cheat Sheets
description: This repository serves as a comprehensive resource for DevOps enthusiasts, providing a collection of cheatsheets and relevant information to help you navigate and master the DevOps role.
theme: just-the-docs

# For jekyll-github-metadata
repository: user-cube/devops-cheatsheet

url: https://user-cube.github.io/devops-cheatsheet/

plugins:
  - jekyll-github-metadata


search_enabled: true
enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

logo: "/assets/images/devops-process.png"

# Add last edit information to footer

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Callouts configuration

callouts:
  warning:
    title: ⚠️ Warning
    color: red
  important:
    title: ⚠️ Important
    color: yellow
